### ISSUE TITLE
cuda_dev

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#14]
@OlehL 
```
Init: cuda_snippets
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_snippets/__init__.py", line 2, in <module>
    from cuda_snippets.dlg_lexers_compare import DlgLexersCompare
  File "/home/user/.config/cudatext/py/cuda_snippets/dlg_lexers_compare.py", line 7, in <module>
    from cuda_dev import dev
ModuleNotFoundError: No module named 'cuda_dev'
```

**Comment by JairoMartinezA** [comment]
Same error as @Alexey-T 

	Traceback (most recent call last):
  	File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\__init__.py", line 2, in <module>
    	from cuda_snippets.dlg_lexers_compare import DlgLexersCompare
  	File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\dlg_lexers_compare.py", line 7, in <module>
    	from cuda_dev import dev
	ModuleNotFoundError: No module named 'cuda_dev'

**Comment by OlehL** [comment]
I forgot about it. Fixed
