### ISSUE TITLE
Loader of snippets don't work now

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#32]
Ubuntu 20.x.
Snips for C_C++ are installed.
After Cud start, I have empty window, I set lexer C or C++ and plugin shows "no snippets for current lexer".
I waited n seconds too (thread needs it?). no help.
@OlehL

**Comment by Alexey-T** [comment]
With such on_start it works, but Cud start is 2sec now
```
    def on_start(self, ed_self):
        self.th = ThSnippetsLoader()
        self.th.start()
        self.snippets, self.glob = sn.load_snippets(DATA_DIR)
```

**Comment by OlehL** [comment]
``` Python
    def on_start(self, ed_self):
        self.th = ThSnippetsLoader()
        self.th.start()

    @property
    def lex_snippets(self):
        self.th.join()  # try add this line
```

Pls test it.

**Comment by Alexey-T** [comment]
This gives on calling Snips menu
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_snippets/__init__.py", line 86, in do_menu
    self.menu_dlg(self.lex_snippets)
  File "/home/user/.config/cudatext/py/cuda_snippets/__init__.py", line 71, in menu_dlg
    names = [str(item) for item in items]
TypeError: 'NoneType' object is not iterable
```

**Comment by OlehL** [comment]
I can't reproduce this on win10x64

**Comment by Alexey-T** [comment]
Let's rework snippet loader - see 
https://github.com/Alexey-T/CudaText/issues/2947
If we rework it, let's don't use threads? it will be fast even w/o threads? (I didnt test) @OlehL
